title: Long Haul Test
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://santanche.github.io/long-haul
baseurl: "/long-haul"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: santanche
   twitter: santanche
   facebook: andre.santanche
   email:

google_analytics: ""